name: Build and push tag

on:
  push:
    tags: [ "*" ]


jobs:

  build-and-push-qwc2-minimal-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push rgdz-thalwil-webgis
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          target: prod
